### ISSUE TITLE
Illegal actions by AI

### ISSUE THREAD

**Issue by dkadish** [Flam3rboy/carcassonne-ai#2]
I tried testing the models that you've trained in [src/results/carcassonne2/](https://github.com/Flam3rboy/carcassonne-ai/tree/main/src/results/carcassonne2) using the testing code in [muzero.py](https://github.com/Flam3rboy/carcassonne-ai/blob/a3a96cc0650538d78bc60e78ecf73b6e013b279d/src/muzero/muzero.py) (running the script, picking `1` to load the model and then `3` to self play) and I'm getting some strange results.

In the screenshot below, you can see that many of the moves being made are illegal. I suspect that this is either an issue with the way that legal actions are defined in https://github.com/Flam3rboy/carcassonne-ai/blob/a3a96cc0650538d78bc60e78ecf73b6e013b279d/src/muzero/carcassonne/utils/action_util.py#L43-L76
Alternatively, it might be that the interpretation of selected actions is off.

![Screen Shot 2022-01-14 at 00 16 53](https://user-images.githubusercontent.com/181041/149502200-033ef33f-c4c5-4ed6-9215-dbec685026e7.png)

I'm happy to help fix the problem, but on first glance, I didn't quite understand how ActionUtil works. Do you have any ideas here? It's also entirely possible that I'm using the code in the wrong way or that I've misunderstood something else, so let me know if that's the case!

**Comment by samuelscheit** [comment]
Disclaimer, I'm still learning ai development and this ai isn't done yet.
What I'm trying to do was to split one carcassonne game move into three parts:
- rotate the card
- place the card
- place meeple

But after many days of training it doesn't get any better.

I think to improve the current model a game move has to be combined into one action.
Also, I'm not sure if the serialized board is in the correct format for the AI to work with it.
